-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."status_absen" AS ENUM('hadir', 'ijin', 'sakit', 'alpha', 'tugas', 'lainnya');--> statement-breakpoint
CREATE SEQUENCE "public"."NilaiKeaktifan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "Provinsi" (
	"kode_provinsi" text PRIMARY KEY NOT NULL,
	"nama_provinsi" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "MataPelajaran" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""MataPelajaran_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"mata_pelajaran" text,
	"tingkat_kelas" text
);
--> statement-breakpoint
CREATE TABLE "AbsenMurid" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""AbsenMurid_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"jadwal_id" bigint NOT NULL,
	"murid_id" integer NOT NULL,
	"status_absen" "status_absen"
);
--> statement-breakpoint
CREATE TABLE "Sekolah" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Sekolah_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nama_sekolah" text,
	"kode_provinsi" text,
	"kode_kabupaten" text,
	"nama_resmi" text
);
--> statement-breakpoint
CREATE TABLE "NilaiTugas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""NilaiTugas_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"murid_id" integer,
	"tugas_id" bigint,
	"nilai" smallint
);
--> statement-breakpoint
CREATE TABLE "NilaiKeaktifan" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nilai_keaktifan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"jadwal_id" bigint NOT NULL,
	"murid_id" integer NOT NULL,
	"nilai" integer NOT NULL,
	"catatan" text,
	CONSTRAINT "NilaiKeaktifan_id_key" UNIQUE("id"),
	CONSTRAINT "nilai_range_check" CHECK ((nilai >= 0) AND (nilai <= 100))
);
--> statement-breakpoint
CREATE TABLE "PenempatanGuru" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""PenempatanGuru_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"guru_id" bigint NOT NULL,
	"sekolah_id" bigint NOT NULL,
	"tanggal_mulai" timestamp with time zone NOT NULL,
	"tanggal_selesai" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "Tugas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Tugas_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"tanggal_tugas" timestamp with time zone,
	"jatuh_tempo" timestamp with time zone,
	"nama_tugas" text,
	"mapel_id" bigint
);
--> statement-breakpoint
CREATE TABLE "Guru" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Guru_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nama_guru" text NOT NULL,
	"nama_panggilan" text
);
--> statement-breakpoint
CREATE TABLE "NilaiUAS" (
	"id" serial PRIMARY KEY NOT NULL,
	"benar" integer NOT NULL,
	"nama_lain_id" integer
);
--> statement-breakpoint
CREATE TABLE "NamaLain" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama_lain" varchar(255) NOT NULL,
	"kelas" varchar(255) NOT NULL,
	"murid_id" integer
);
--> statement-breakpoint
CREATE TABLE "Murid" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" varchar(255) NOT NULL,
	"kelas" varchar(255) NOT NULL,
	"nomor_absen" varchar(255) NOT NULL,
	"kelas_id" bigint NOT NULL,
	"NISN" text,
	"NIS" text,
	CONSTRAINT "Murid_NISN_key" UNIQUE("NISN"),
	CONSTRAINT "Murid_NISN_check" CHECK (length("NISN") = 10)
);
--> statement-breakpoint
CREATE TABLE "Kelas" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""Kelas_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nama_kelas" text,
	"tingkat" text,
	"sekolah_id" bigint
);
--> statement-breakpoint
CREATE TABLE "Jadwal" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""JadwalGuru_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"kelas_id" bigint NOT NULL,
	"waktu_mulai" timestamp with time zone NOT NULL,
	"waktu_selesai" timestamp with time zone NOT NULL,
	"mapel_id" bigint NOT NULL,
	"penempatan_guru_id" bigint
);
--> statement-breakpoint
CREATE TABLE "Kabupaten" (
	"kode_kabupaten" text NOT NULL,
	"kode_provinsi" text NOT NULL,
	"nama_kabupaten" text NOT NULL,
	CONSTRAINT "Kabupaten_pkey" PRIMARY KEY("kode_kabupaten","kode_provinsi")
);
--> statement-breakpoint
CREATE TABLE "Kecamatan" (
	"kode_provinsi" text NOT NULL,
	"kode_kabupaten" text NOT NULL,
	"nama_kecamatan" text NOT NULL,
	"kode_kecamatan" text NOT NULL,
	CONSTRAINT "Kecamatan_pkey" PRIMARY KEY("kode_provinsi","kode_kabupaten","kode_kecamatan")
);
--> statement-breakpoint
CREATE TABLE "DesaKelurahan" (
	"kode_provinsi" text NOT NULL,
	"kode_kabupaten" text NOT NULL,
	"kode_kecamatan" text NOT NULL,
	"kode_desa_kelurahan" text NOT NULL,
	"nama_desa_kelurahan" text NOT NULL,
	CONSTRAINT "DesaKelurahan_pkey" PRIMARY KEY("kode_provinsi","kode_kabupaten","kode_kecamatan","kode_desa_kelurahan")
);
--> statement-breakpoint
ALTER TABLE "AbsenMurid" ADD CONSTRAINT "AbsenMurid_jadwal_id_fkey" FOREIGN KEY ("jadwal_id") REFERENCES "public"."Jadwal"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "AbsenMurid" ADD CONSTRAINT "AbsenMurid_murid_id_fkey" FOREIGN KEY ("murid_id") REFERENCES "public"."Murid"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Sekolah" ADD CONSTRAINT "Sekolah_kode_kabupaten_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi","kode_kabupaten") REFERENCES "public"."Kabupaten"("kode_kabupaten","kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Sekolah" ADD CONSTRAINT "Sekolah_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi") REFERENCES "public"."Provinsi"("kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NilaiTugas" ADD CONSTRAINT "NilaiTugas_murid_id_fkey" FOREIGN KEY ("murid_id") REFERENCES "public"."Murid"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NilaiTugas" ADD CONSTRAINT "NilaiTugas_tugas_id_fkey" FOREIGN KEY ("tugas_id") REFERENCES "public"."Tugas"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NilaiKeaktifan" ADD CONSTRAINT "NilaiKeaktifan_jadwal_id_fkey" FOREIGN KEY ("jadwal_id") REFERENCES "public"."Jadwal"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NilaiKeaktifan" ADD CONSTRAINT "NilaiKeaktifan_murid_id_fkey" FOREIGN KEY ("murid_id") REFERENCES "public"."Murid"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "PenempatanGuru" ADD CONSTRAINT "PenempatanGuru_guru_id_fkey" FOREIGN KEY ("guru_id") REFERENCES "public"."Guru"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "PenempatanGuru" ADD CONSTRAINT "PenempatanGuru_sekolah_id_fkey" FOREIGN KEY ("sekolah_id") REFERENCES "public"."Sekolah"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Tugas" ADD CONSTRAINT "Tugas_mapel_id_fkey" FOREIGN KEY ("mapel_id") REFERENCES "public"."MataPelajaran"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NilaiUAS" ADD CONSTRAINT "nilai_nama_lain_id_nama_lain_id_fk" FOREIGN KEY ("nama_lain_id") REFERENCES "public"."NamaLain"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "NamaLain" ADD CONSTRAINT "NamaLain_murid_id_fkey" FOREIGN KEY ("murid_id") REFERENCES "public"."Murid"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Murid" ADD CONSTRAINT "Murid_kelas_id_fkey" FOREIGN KEY ("kelas_id") REFERENCES "public"."Kelas"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Kelas" ADD CONSTRAINT "Kelas_sekolah_id_fkey" FOREIGN KEY ("sekolah_id") REFERENCES "public"."Sekolah"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Jadwal" ADD CONSTRAINT "JadwalGuru_kelas_id_fkey" FOREIGN KEY ("kelas_id") REFERENCES "public"."Kelas"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Jadwal" ADD CONSTRAINT "Jadwal_mapel_id_fkey" FOREIGN KEY ("mapel_id") REFERENCES "public"."MataPelajaran"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Jadwal" ADD CONSTRAINT "Jadwal_penempatan_guru_id_fkey" FOREIGN KEY ("penempatan_guru_id") REFERENCES "public"."PenempatanGuru"("id") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Kabupaten" ADD CONSTRAINT "Kabupaten_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi") REFERENCES "public"."Provinsi"("kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Kecamatan" ADD CONSTRAINT "Kecamatan_kode_kabupaten_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi","kode_kabupaten") REFERENCES "public"."Kabupaten"("kode_kabupaten","kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "Kecamatan" ADD CONSTRAINT "Kecamatan_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi") REFERENCES "public"."Provinsi"("kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "DesaKelurahan" ADD CONSTRAINT "DesaKelurahan_kode_kabupaten_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi","kode_kabupaten") REFERENCES "public"."Kabupaten"("kode_kabupaten","kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "DesaKelurahan" ADD CONSTRAINT "DesaKelurahan_kode_kecamatan_kode_kabupaten_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi","kode_kabupaten","kode_kecamatan") REFERENCES "public"."Kecamatan"("kode_provinsi","kode_kabupaten","kode_kecamatan") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "DesaKelurahan" ADD CONSTRAINT "DesaKelurahan_kode_provinsi_fkey" FOREIGN KEY ("kode_provinsi") REFERENCES "public"."Provinsi"("kode_provinsi") ON DELETE set null ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "nilai_keaktifan_jadwal_id_idx" ON "NilaiKeaktifan" USING btree ("jadwal_id" int8_ops);--> statement-breakpoint
CREATE INDEX "nilai_keaktifan_murid_id_idx" ON "NilaiKeaktifan" USING btree ("murid_id" int4_ops);
*/